apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: ivia-operator-with-config-template
metadata:
  creationTimestamp: null
  name: ivia-operator-with-config-template
  annotations:
    openshift.io/display-name: IBM Verify Identity Access Appliance (Operator) Template
    iconClass: icon-sso
    description: IBM Verify Identity Access Appliance deployment using the verify-identity-access-operator
    openshift.io/long-description: This template deploys the core services required for an IBM
      Verify Identity Access environment.  You must have the IBM Verify Identity Access Operator
      installed. The operator secret can be read from the namespace that the operator's controller
      pod is deployed to.
    openshift.io/documentation-url: https://ibm.biz/isamdocker
    openshift.io/provider-display-name: Lachlan Gleeson
    openshift.io/support-url: https://ibm.biz/iamcommunity
    tags: ibm, isam, isva, ivia
message: |-

  Application Name: ${APP_NAME}

  The following services have been created in your project:
    - ${CONFIG_SERVICE}
    - ${RUNTIME_SERVICE}
    - ${WEBSEAL_SERVICE}
  
  Note:: The verify-access-operator secret must be updated with the rw.pwd to start. This property
        can be found in the secret of the same name in the namespace where the operator's controller 
        pod is deployed.
  
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    labels:
      app: ${APP_NAME}-core
      name: ${APP_NAME}-config
    name: ${APP_NAME}-config
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        name: ${APP_NAME}-config
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APP_NAME}-core
          name: ${APP_NAME}-config
      spec:
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
        - name: ${APP_NAME}-config
          image: ${IVIA_IMAGE_NAME}-config:${IVIA_VERSION}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            exec:
              command:
              - /sbin/health_check.sh
              - livenessProbe
            periodSeconds: 30
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: 9443
              path: /core/login
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 2
          volumeMounts:
          - mountPath: /var/shared
            name: ${APP_NAME}-config
          - mountPath: /var/application.logs
            name: ${APP_NAME}-config-logs
          - mountPath: /tmp/verify-access-operator.crt
            name: verify-access-operator
            subPath: tls.cert
            readOnly: true
          env:
            - name: SNAPSHOT_ID
              value: ${SNAPSHOT_ID}
            - name: CONTAINER_TIMEZONE
              value: ${TIMEZONE}
            - name: CONFIG_SERVICE_TLS_CACERT
              value: operator
            - name: CONFIG_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: url
            - name: CONFIG_SERVICE_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: user
            - name: CONFIG_SERVICE_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: verify-access-operator
                  key: rw.pwd
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${APP_NAME}-config
          emptyDir: {}
        - name: ${APP_NAME}-config-logs
          emptyDir: {}
        - name: verify-access-operator
          secret:
            secretName: verify-access-operator

- apiVersion: ibm.com/v1
  kind: IBMSecurityVerifyAccess
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    labels:
      name: ${APP_NAME}-wrp
    name: ${APP_NAME}-wrp
  spec:
    image: ${IVIA_IMAGE_NAME}-wrp:${IVIA_VERSION}
    # fixpacks:
    #   - ${FIXPACKS}
    # volumes:
    #   - name: ${VOLUMES}
    snapshotId: ${SNAPSHOT_ID}
    instance: ${WRP_INSTANCE}
    language: ${LANGUAGE}
    replicas: 1

- apiVersion: ibm.com/v1
  kind: IBMSecurityVerifyAccess
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    labels:
      name: ${APP_NAME}-runtime
    name: ${APP_NAME}-runtime
  spec:
    image: ${IVIA_IMAGE_NAME}-runtime:${IVIA_VERSION}
    # fixpacks:
    #   - ${FIXPACKS}
    # volumes:
    #   - name: ${VOLUMES}
    snapshotId: ${SNAPSHOT_ID}
    language: ${LANGUAGE}
    replicas: 1

- apiVersion: ibm.com/v1
  kind: IBMSecurityVerifyAccess
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    labels:
      name: ${APP_NAME}-dsc
    name: ${APP_NAME}-dsc
  spec:
    image: ${IVIA_IMAGE_NAME}-dsc:${IVIA_VERSION}
    # fixpacks:
    #   - ${FIXPACKS}
    # volumes:
    #   - name: ${VOLUMES}
    instance: ${DSC_INSTANCE}
    snapshotId: ${SNAPSHOT_ID}
    language: ${LANGUAGE}
    replicas: 1

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${CONFIG_SERVICE}
    labels:
      app: ${APP_NAME}-core
      name: ${APP_NAME}-config
  spec:
    ports:
    - name: lmi
      port: 9443
      protocol: TCP
    selector:
      name: ${APP_NAME}-config
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${WEBSEAL_SERVICE}
    labels:
      app: ${APP_NAME}-core
      name: ${APP_NAME}-wrp
  spec:
    ports:
    - name: wrp-default
      port: 9443
      protocol: TCP
    selector:
      name: ${APP_NAME}-wrp
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${RUNTIME_SERVICE}
    labels:
      app: ${APP_NAME}-core
      name: ${APP_NAME}-runtime
  spec:
    ports:
    - name: runtime
      port: 9443
      protocol: TCP
    selector:
      name: ${APP_NAME}-runtime
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}


- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${DSC_SERVICE}
    labels:
      app: ${APP_NAME}-core
      name: ${APP_NAME}-dsc
  spec:
    ports:
    - name: service
      port: 9443
      protocol: TCP
    - name: replica
      port: 9444
      protocol: TCP
    selector:
      name: ${APP_NAME}-dsc
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

parameters:
  - displayName: Application Name
    description: This is the name for the application which is used to create unique object names in the cluster.
    name: APP_NAME
    value: ivia
  - displayName: Verify Identity Access Image Name 
    description: This is the name used to identify verify identity access images. The supporting containers should have a
       \'-wrp\' or \'-runtime\' suffixes. This value should include the registry domain.
    name: IVIA_IMAGE_NAME
    value: icr.io/ivia/ivia
  - displayName: IVIA Image Version
    description: The tag that will be used to pull the ibmcom/isam image.
    name: IVIA_VERSION
    value: 11.0.2.0
  - displayName: Snapshot Id
    description: The snapshot id to use.
    name: SNAPSHOT_ID
    value: operator-template
  - displayName: Reverse Proxy Instance
    description: The name of the wrp instance to start in the reverse proxy runtime container.
    name: WRP_INSTANCE
    value: default
  - displayName: Distributed Session Cache Instance
    description: The name of the distributed session cache instance to start in the reverse proxy runtime container.
    name: DSC_INSTANCE
    value: "1"
  - displayName: Config Service Name
    description: The name for the config service.  Also used as the hostname for connections within the cluster.
    name: CONFIG_SERVICE
    value: iviaconfig
  - displayName: Runtime Service Name
    description: The name for the runtime service.  Also used as the hostname for connections within the cluster.
    name: RUNTIME_SERVICE
    value: iviaruntime
  - displayName: Webseal Service Name
    description: The name for the webseal service.  Also used as the hostname for connections within the cluster.
    name: WEBSEAL_SERVICE
    value: iviawebseal
  - displayName: DSC Service Name
    description: The name for the distributed session cache service.  Also used as the hostname for connections within the cluster.
    name: DSC_SERVICE
    value: iviadsc
  - displayName: Timezone
    description: The timezone for message logging (e.g. Europe/London)
    name: TIMEZONE
    value: Etc/UTC
  - displayName: Language
    description: The language for message logging (e.g. en_US.utf8, fr_FR.utf8)
    name: LANGUAGE
    value: en_US.utf8