
#
# This file contains the default values used by the helm chart installation.
#

###############################################################################
# Global configuration which is available to all sub-charts

global:
  # Common image variables
  image:
    repository:   ibmcom/verify-access:10.0.0.0
    dbrepository: ibmcom/verify-access-postgresql:10.0.0.0
    ldaprepository: ibmcom/verify-access-openldap:10.0.0.0
    pullPolicy:   IfNotPresent

  # Image credentials (not needed unless using a private repository)
  imageCredentials:
    dockerSecret: ""

  # Container configuration.
  container:
    snapshot:            ""
    fixpacks:            ""
    adminSecret:         ""
    autoReloadInterval:
    timezone:            "Etc/UTC"

  # Persistence Storage
  persistence:
    enabled:                true
    useDynamicProvisioning: true

###############################################################################
# Configuration container variables.

isvaconfig:

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 1Gi
      cpu:    1000m
    limits:
      memory: 2Gi
      cpu:    2000m

  # Service Configuration.
  service:
    type: NodePort
    nodePort:

  # Data Volume
  dataVolume:

    # Specify the name of the Existing Claim to be used by your application.
    # An empty string means that an existing claim will not be used.
    existingClaimName: ""

    # Specify the name of the storage class.  Any empty string means that we
    # won't use a storage class.
    storageClassName: ""

    size:        20Gi

###############################################################################
# Web Reverse Proxy container variables.

isvawrp:

  # Container configuration.
  container:
    instances:
     - name: default
       nodePort:
       replicas: 1

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

  # Service Configuration.
  service:
    type: NodePort
    nodePort:

###############################################################################
# Runtime container variables.

isvaruntime:

  # Container configuration.
  container:
    enabled:  false
    replicas: 1

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 1Gi
      cpu:    1000m
    limits:
      memory: 2Gi
      cpu:    2000m

###############################################################################
# DSC container variables.

isvadsc:

  # Container configuration.
  container:
    enabled:    false
    useReplica: true

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

###############################################################################
# postgresql container variables.

isvapostgresql:

  # Container configuration.
  container:
    enabled: false
    keySecretName: ""

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

  # Data Volume
  dataVolume:

    # Specify the name of the Existing Claim to be used by your application.
    # An empty string means that an existing claim will not be used.
    existingClaimName: ""

    # Specify the name of the storage class.  Any empty string means that we
    # won't use a storage class.
    storageClassName: ""

    size:        20Gi

###############################################################################
# openldap container variables.

isvaopenldap:

  # Container configuration.
  container:
    enabled: false
    keySecretName: ""

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

  # Data Volume
  dataVolume:

    # Specify the name of the Existing Claim to be used by your application.
    # An empty string means that an existing claim will not be used.
    existingClaimName: ""

    # Specify the name of the storage class.  Any empty string means that we
    # won't use a storage class.
    storageClassName: ""

    size:        20Gi
