 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: iamlab-isvaconfig
   annotations:
     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
 spec:
  tls:
  - hosts:
    - lmi.iamlab.ibm.com
  rules:
  - host: lmi.iamlab.ibm.com
    http:
      paths:
      - path: /
        backend:
          serviceName: iamlab-isvaconfig
          servicePort: 9443
