apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        rewrite {
           name regex isvaconfig iamlab-isvaconfig.default.svc.cluster.local
           answer name iamlab-isvaconfig.default.svc.cluster.local isvaconfig
        }
        rewrite {
           name regex isvawrprp1 iamlab-isvawrp-rp1.default.svc.cluster.local
           answer name iamlab-isvawrp-rp1.default.svc.cluster.local isvawrprp1
        }
        rewrite {
           name regex postgresql iamlab-isvapostgresql.default.svc.cluster.local
           answer name iamlab-isvapostgresql.default.svc.cluster.local postgresql
        }
        rewrite {
           name regex isvaruntime iamlab-isvaruntime.default.svc.cluster.local
           answer name iamlab-isvaruntime.default.svc.cluster.local isvaruntime
        }
        rewrite {
           name regex isvadsc iamlab-isvadsc-primary.default.svc.cluster.local
           answer name iamlab-isvadsc-primary.default.svc.cluster.local isvadsc
        }
        rewrite {
           name regex openldap iamlab-isvaopenldap.default.svc.cluster.local
           answer name iamlab-isvaopenldap.default.svc.cluster.local openldap
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
