{{- include "sch.config.init" (list . "isvawrp.sch.chart.config.values") -}}

{{- $dot := . }}
{{- range $index, $inst := .Values.container.instances }}
{{- $instance := lower $inst.name }}
{{- $index    := (printf "%d" $index) }}

#
# This file contains the definition for the service provides by this helm
# chart.
#

apiVersion: v1
kind: Service

metadata:
  name: {{ include "wrp.name" (list $dot $instance) }}-admin
  labels:
{{ include "sch.metadata.labels.standard" (list $dot "") | indent 4 }}

spec:
  type: ClusterIP

  ports:
   - name: {{ include "wrp.admin.service.name" (list $dot $index) }}
     port: {{ template "admin.port" $dot }}

  selector:
    app: {{ include "wrp.name" (list $dot $instance) }}

---

{{- end -}}
